# Generated by Django 5.0.3 on 2025-06-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AraxMSS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
    ]
